# Follow instructions on:
# https://blog.rstudio.org/2016/03/09/r-on-travis-ci/

# A few blocks in here can be removed when Travis updates its Ubuntu image past 
# trusty. They are marked with TRUSTY for easy grepping.

language: r

# TRUSTY: Change version when 16.04 image is available.
dist: trusty
sudo: required

env:
  global:
    # TODO: `make -j2` interleaves output lines from simultaneous processes.
    # Would be nice to fix by adding `-Otarget`, but not supported in Make 3.x.
    # When Travis updates, check for Make 4 and add -O if available.
    - MAKEFLAGS="-j2"
    - PGHOST=localhost

cache: 
  - directories:
    - .install
    - .check
    - .test
    - .doc
  - packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:nschloe/hdf5-backports'
      - sourceline: 'ppa:ubuntugis/ppa' # for GDAL 2 binaries
    packages:
      - bc
      - curl
      - gdal-bin
      - jags
      - libcurl4-openssl-dev
      - libgdal-dev
      - libgmp-dev
      - libhdf5-dev
      - liblapack-dev
      - libnetcdf-dev
      - libproj-dev
      - libudunits2-dev
      - netcdf-bin
      - pandoc
      - python-dev
      - tcl
      - tcl-dev
      - udunits-bin
      # R package binaries from c2d4u
      - r-bioc-biocinstaller
      - r-cran-ape
      - r-cran-curl
      - r-cran-devtools
      - r-cran-dplyr
      - r-cran-ggplot2
      - r-cran-httr
      - r-cran-igraph
      - r-cran-lme4
      - r-cran-matrixstats
      - r-cran-mcmcpack
      - r-cran-raster
      - r-cran-rcpp
      - r-cran-rcurl
      - r-cran-redland
      - r-cran-rncl
      - r-cran-roxygen2
      - r-cran-shiny
      - r-cran-testthat
      - r-cran-tidyverse
      - r-cran-xml
      - r-cran-xml2

  
## notifications should go to gitter
notifications:
  slack:
    # Slack token created by Chris Black, 2018-02-17
    secure: "DHHSNmiCf71SLa/FFSqx9oOnJjJt2GHYk7NsFIBb9ZY10RvQtIPfaoNxkPjqu9HLyZWJSFtg/uNKKplEHc6W80NoXyqoTvwOxTPjMaViXaCNqsmzjjR/JaCWT/oWGXyAw0VX3S8cwuIexlKQGgZwJpIzoVOZqUrDrHI/O17kZoM="
  email:
    on_success: always
    on_failure: always

## list of services to be running
services:
  - docker

install: skip

# not used directly, but defines YAML reference to be inserted below
_install: &installscript
  - set -e
  - pushd $HOME
  - curl -o sipnet_unk.tar.gz http://isda.ncsa.illinois.edu/~kooper/EBI/sipnet_unk.tar.gz
  - tar zxf sipnet_unk.tar.gz
  - cd sipnet_unk
  - make
  - popd
  - sudo service postgresql stop
  - docker run --detach --rm --name postgresql --publish 5432:5432 mdillon/postgis:9.6-alpine
  - echo -n "Waiting for Postgres to start...";
    until psql -U postgres -c 'select 1' >/dev/null 2>&1;
      do echo -n ".";
      sleep 1;
    done;
    echo " OK"
  - psql -q -o /dev/null -U postgres -c "CREATE ROLE BETY WITH LOGIN CREATEDB SUPERUSER CREATEROLE UNENCRYPTED PASSWORD 'bety'";
  - psql -q -o /dev/null -U postgres -c "CREATE DATABASE bety OWNER bety;"
  - curl -o bety.sql http://isda.ncsa.illinois.edu/~kooper/PEcAn/data/bety.sql
  - psql -q -o /dev/null -U postgres < bety.sql
  - rm bety.sql
  - ./scripts/add.models.sh
  - chmod +x book_source/deploy.sh
  - chmod +x documentation/tutorials/deploy.sh
  - echo 'Installing PEcAn packages'
  # - make document
  # TODO: Would probably be faster to use -j2 NCPUS=1 as for other steps,
  # but many dependency compilations seem not parallel-safe.
  # More debugging needed.
  - NCPUS=2 make -j1 .install/"$TEST_PKG"
  # TODO this ought to run after tests too, to ensure they clean up correctly
  # Maybe as a before_cache step?
  - if [[ `git status -s` ]]; then
      echo "These files were changed by the build process:";
      git status -s;
      echo "Have you run devtools::check and commited any updated Roxygen outputs?";
      exit 1;
    fi
  - set +e


stages:
  - setup
  - test
  # - integration
  # - deploy

jobs:
  include:
    - stage: setup
      r: release
      install: *installscript
      script: skip
    - r: 3.4
      install: *installscript
      script: skip
    - r: devel
      install: *installscript
      script: skip
    - stage: test
      r: release
      script: make .check/base/all
    - r: release
      script: make .check/base/db
    - r: release
      script: make .check/base/logger
    - r: release
      script: make .check/base/qaqc
    - r: release
      script: make .check/base/remote
    - r: release
      script: make .check/base/settings
    - r: release
      script: make .check/base/utils
    - r: release
      script: make .check/base/visualization
    - r: release
      script: make .check/base/workflow
    - r: release
      script: make .check/models/biocro
    - r: release
      script: make .check/models/clm45
    - r: release
      script: make .check/models/dalec
    - r: release
      script: make .check/models/ed
    - r: release
      script: make .check/models/fates
    - r: release
      script: make .check/models/gday
    - r: release
      script: make .check/models/jules
    - r: release
      script: make .check/models/linkages
    - r: release
      script: make .check/models/lpjguess
    - r: release
      script: make .check/models/maat
    - r: release
      script: make .check/models/maespa
    - r: release
      script: make .check/models/preles
    - r: release
      script: make .check/models/sipnet
    - r: release
      script: make .check/models/template
    - r: release
      script: make .check/modules/allometry
    - r: release
      script: make .check/modules/assim.batch
    - r: release
      script: make .check/modules/assim.sequential
    - r: release
      script: make .check/modules/benchmark
    - r: release
      script: make .check/modules/data.atmosphere
    - r: release
      script: make .check/modules/data.hydrology
    - r: release
      script: make .check/modules/data.land
    - r: release
      script: make .check/modules/data.mining
    - r: release
      script: make .check/modules/data.remote
    - r: release
      script: make .check/modules/emulator
    - r: release
      script: make .check/modules/meta.analysis
    - r: release
      script: make .check/modules/photosynthesis
    - r: release
      script: make .check/modules/priors
    - r: release
      script: make .check/modules/rtm
    - r: release
      script: make .check/modules/uncertainty
    - r: 3.4
      script: make .check/base/all
    - r: 3.4
      script: make .check/base/db
    - r: 3.4
      script: make .check/base/logger
    - r: 3.4
      script: make .check/base/qaqc
    - r: 3.4
      script: make .check/base/remote
    - r: 3.4
      script: make .check/base/settings
    - r: 3.4
      script: make .check/base/utils
    - r: 3.4
      script: make .check/base/visualization
    - r: 3.4
      script: make .check/base/workflow
    - r: 3.4
      script: make .check/models/biocro
    - r: 3.4
      script: make .check/models/clm45
    - r: 3.4
      script: make .check/models/dalec
    - r: 3.4
      script: make .check/models/ed
    - r: 3.4
      script: make .check/models/fates
    - r: 3.4
      script: make .check/models/gday
    - r: 3.4
      script: make .check/models/jules
    - r: 3.4
      script: make .check/models/linkages
    - r: 3.4
      script: make .check/models/lpjguess
    - r: 3.4
      script: make .check/models/maat
    - r: 3.4
      script: make .check/models/maespa
    - r: 3.4
      script: make .check/models/preles
    - r: 3.4
      script: make .check/models/sipnet
    - r: 3.4
      script: make .check/models/template
    - r: 3.4
      script: make .check/modules/allometry
    - r: 3.4
      script: make .check/modules/assim.batch
    - r: 3.4
      script: make .check/modules/assim.sequential
    - r: 3.4
      script: make .check/modules/benchmark
    - r: 3.4
      script: make .check/modules/data.atmosphere
    - r: 3.4
      script: make .check/modules/data.hydrology
    - r: 3.4
      script: make .check/modules/data.land
    - r: 3.4
      script: make .check/modules/data.mining
    - r: 3.4
      script: make .check/modules/data.remote
    - r: 3.4
      script: make .check/modules/emulator
    - r: 3.4
      script: make .check/modules/meta.analysis
    - r: 3.4
      script: make .check/modules/photosynthesis
    - r: 3.4
      script: make .check/modules/priors
    - r: 3.4
      script: make .check/modules/rtm
    - r: 3.4
      script: make .check/modules/uncertainty
    - r: devel
      script: make .check/base/all
    - r: devel
      script: make .check/base/db
    - r: devel
      script: make .check/base/logger
    - r: devel
      script: make .check/base/qaqc
    - r: devel
      script: make .check/base/remote
    - r: devel
      script: make .check/base/settings
    - r: devel
      script: make .check/base/utils
    - r: devel
      script: make .check/base/visualization
    - r: devel
      script: make .check/base/workflow
    - r: devel
      script: make .check/models/biocro
    - r: devel
      script: make .check/models/clm45
    - r: devel
      script: make .check/models/dalec
    - r: devel
      script: make .check/models/ed
    - r: devel
      script: make .check/models/fates
    - r: devel
      script: make .check/models/gday
    - r: devel
      script: make .check/models/jules
    - r: devel
      script: make .check/models/linkages
    - r: devel
      script: make .check/models/lpjguess
    - r: devel
      script: make .check/models/maat
    - r: devel
      script: make .check/models/maespa
    - r: devel
      script: make .check/models/preles
    - r: devel
      script: make .check/models/sipnet
    - r: devel
      script: make .check/models/template
    - r: devel
      script: make .check/modules/allometry
    - r: devel
      script: make .check/modules/assim.batch
    - r: devel
      script: make .check/modules/assim.sequential
    - r: devel
      script: make .check/modules/benchmark
    - r: devel
      script: make .check/modules/data.atmosphere
    - r: devel
      script: make .check/modules/data.hydrology
    - r: devel
      script: make .check/modules/data.land
    - r: devel
      script: make .check/modules/data.mining
    - r: devel
      script: make .check/modules/data.remote
    - r: devel
      script: make .check/modules/emulator
    - r: devel
      script: make .check/modules/meta.analysis
    - r: devel
      script: make .check/modules/photosynthesis
    - r: devel
      script: make .check/modules/priors
    - r: devel
      script: make .check/modules/rtm
    - r: devel
      script: make .check/modules/uncertainty

    # - stage: integration
    #   # if: branch IN (master, develop, ^release)
    #   script:
    #     - set -e
    #     - echo 'Testing Integration';
    #     - ./tests/integration.sh travis;
    #     - set +e
    # - stage: deploy
    #   # if: branch IN (master, develop, ^release)
    #   script:
    #     - set -e
    #     - echo 'Building Book'
    #     - pushd book_source
    #     - make
    #     - popd
    #     - echo 'Building Tutorials'
    #     - pushd documentation/tutorials
    #     - make build deploy
    #     - popd
    #     - set +e
